# Generated by Django 4.2.6 on 2025-08-09 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宠物名称')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='品种')),
                ('gender', models.CharField(choices=[('M', '雄性'), ('F', '雌性'), ('U', '未知')], max_length=1, verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄（月）')),
                ('size', models.CharField(choices=[('S', '小型'), ('M', '中型'), ('L', '大型')], max_length=1, verbose_name='体型')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重（kg）')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='毛色')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可领养')),
                ('location', models.CharField(max_length=100, verbose_name='所在地点')),
                ('intake_date', models.DateField(default=django.utils.timezone.now, verbose_name='救助/入住日期')),
                ('health_status', models.CharField(choices=[('HEALTHY', '健康'), ('MINOR_ISSUES', '轻微健康问题'), ('CHRONIC_CONDITION', '慢性疾病'), ('RECOVERING', '恢复中'), ('NEEDS_TREATMENT', '需要治疗'), ('UNKNOWN', '未知')], default='HEALTHY', max_length=30, verbose_name='健康状况')),
                ('vaccination_status', models.BooleanField(default=False, verbose_name='已接种疫苗')),
                ('sterilization_status', models.BooleanField(default=False, verbose_name='已绝育')),
                ('behavior', models.TextField(blank=True, verbose_name='行为特征')),
                ('good_with_kids', models.BooleanField(default=False, verbose_name='适合与儿童相处')),
                ('good_with_pets', models.BooleanField(default=False, verbose_name='适合与其他宠物相处')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='简要描述')),
                ('cover', models.FileField(upload_to=pet.models.PathAndRename('pet_cover'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='封面图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hobbies', models.CharField(blank=True, max_length=200, verbose_name='喜好')),
                ('habits', models.TextField(blank=True, verbose_name='特殊习惯')),
                ('rescue_date', models.DateField(verbose_name='救助时间')),
                ('rescue_location', models.CharField(blank=True, max_length=200, verbose_name='救助地点')),
            ],
            options={
                'verbose_name': '宠物管理',
                'verbose_name_plural': '宠物管理',
            },
        ),
        migrations.CreateModel(
            name='PetCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('image', models.ImageField(upload_to=pet.models.PathAndRename('pet_carousel/'), verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='宠物类别')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '宠物类别',
                'verbose_name_plural': '宠物类别',
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pet.models.PathAndRename('pet_photos'), verbose_name='照片')),
                ('shooting_time', models.DateField(verbose_name='拍摄时间')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='照片描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('location', models.CharField(max_length=255, verbose_name='拍照地点')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_photo_pet', to='pet.pet', verbose_name='宠物')),
                ('shooting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_photo_shooting_user', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '宠物照片',
                'verbose_name_plural': '宠物照片',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.petcategory', verbose_name='种类'),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(verbose_name='检查日期')),
                ('diagnosis', models.TextField(verbose_name='诊断结果')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='治疗方案')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_record_pet', to='pet.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '通过'), ('REJECTED', '拒绝')], default='PENDING', max_length=20, verbose_name='申请状态')),
                ('reason', models.TextField(verbose_name='领养理由')),
                ('experience', models.CharField(blank=True, max_length=255, verbose_name='养宠经验')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comments', models.CharField(blank=True, max_length=255, verbose_name='审核备注')),
                ('application_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_application_application_user', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_application_pet', to='pet.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '领养申请',
                'verbose_name_plural': '领养申请',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='宠物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏管理',
                'verbose_name_plural': '收藏管理',
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
