# Generated by Django 4.2.6 on 2026-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='review_date',
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', '雄性'), ('F', '雌性')], max_length=1, verbose_name='性别'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
