# Generated by Django 4.2.6 on 2025-05-25 07:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]{5,20}$', '仅允许字母、数字和下划线（5-20位）')], verbose_name='账号')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[\\u4e00-\\u9fa5a-zA-Z0-9_]{2,20}$', '2-20位中文/英文/数字')], verbose_name='用户名')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to=user.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='头像')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('identity_type', models.CharField(choices=[('ID', '居民身份证'), ('PP', '护照'), ('OT', '其他证件')], max_length=10, verbose_name='证件类型')),
                ('identity_number', models.CharField(max_length=30, unique=True, verbose_name='证件号码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
